### ISSUE TITLE
Project name is misleading

### ISSUE THREAD

**Issue by lokirobotics** [FinReach/bulk-change-tenants-text-tool#3]
The name of the project implies that it's for working with ZKG15 texts. This is wrong. The aim of this tool was to provide a way to bulk-change tenant texts in switch.

The following changes should be made to clarify what the project is about and what it does:

- [x] Rename the repository. The new name should indicate what the tool actually does
- [ ] Update the readme.
- [ ] Update the configuration parameters (ZKG_COLLECTION...)

**Comment by welsoncosta** [comment]
The project name was changed, other issues are being addressed.
