### ISSUE TITLE
Configuration Issues

### ISSUE THREAD

**Issue by lokirobotics** [FinReach/bulk-change-tenants-text-tool#5]
The `ZKG_COLLECTION` configuration item is highly dangerous. Switch stores all the tenant text's in a collection with a fixed name. Making the collection name configurable gives the operator the possibility to damage the switch database. The text collection should be fixed or, at least, be very hard to change from an operators perspective. The text collection name hasn't been changed since the app exists (that is four years now). I don't expect the collection name to change anytime soon.

**Comment by welsoncosta** [comment]
Removed the configuration
